[build]
  command = "pnpm run build"
  functions = "dist"
  publish = "dist/public"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/index:*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  DATABASE_URL = ""
  JWT_SECRET = ""
  VITE_APP_ID = ""
  OAUTH_SERVER_URL = "https://api.manus.im"
  VITE_OAUTH_PORTAL_URL = "https://oauth.manus.im"
  VITE_APP_TITLE = "KOON 7R"
  VITE_APP_LOGO = "logo.png"
  TELEGRAM_BOT_TOKEN = ""
  TELEGRAM_CHAT_ID = ""
  BUILT_IN_FORGE_API_URL = ""
  BUILT_IN_FORGE_API_KEY = ""
